[package]
name = "mock_messenger"
version = "0.1.0"
edition = "2021"
# default-run = "mock_messenger"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
